import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { Eye, EyeOff, CheckCircle2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import sealAsset from "@/assets/sceau-cameroun.jfif.asset.json";
import panoramaAsset from "@/assets/panorama-douala.jpg.asset.json";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/reset-password")({head:()=>({meta:[{title:"Nouveau mot de passe — Services municipaux"},{name:"description",content:"Créez un nouveau mot de passe pour votre compte municipal."},{property:"og:title",content:"Nouveau mot de passe — Services municipaux"},{property:"og:description",content:"Retrouvez l'accès sécurisé à votre espace citoyen."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Reset});
function Reset(){const[p,setP]=useState("");const[c,setC]=useState("");const[show,setShow]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();if(!window.location.hash.includes("type=recovery")){setError("Ce lien est invalide ou a expiré.");return}if(p!==c){setError("Les mots de passe ne correspondent pas.");return}const{error}=await supabase.auth.updateUser({password:p});if(error)setError(error.message);else setDone(true)}return <main className="reset-page" style={{backgroundImage:`linear-gradient(var(--auth-overlay),var(--auth-overlay)),url(${panoramaAsset.url})`}}><form className="auth-card" onSubmit={submit}><div className="seal"><img src={sealAsset.url} alt="Sceau du Cameroun"/><strong>République du Cameroun</strong><span>Paix · Travail · Patrie</span></div>{done?<div className="success-state"><CheckCircle2/><h1>Mot de passe modifié</h1><p>Vous pouvez désormais vous connecter.</p><Button asChild><Link to="/">Aller à la connexion</Link></Button></div>:<><div className="auth-title"><span>Sécurité du compte</span><h1>Nouveau mot de passe</h1><p>Choisissez au moins 8 caractères.</p></div><label className="field"><span>Nouveau mot de passe *</span><div className="password-wrap"><Input type={show?"text":"password"} required minLength={8} value={p} onChange={e=>setP(e.target.value)}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label className="field"><span>Confirmer *</span><Input type="password" required minLength={8} value={c} onChange={e=>setC(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<Button>Enregistrer le mot de passe</Button></>}</form></main>}
