import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import {
  ArrowLeft, ArrowRight, Bell, Building2, CalendarDays, Camera, Check, CheckCircle2,
  ChevronRight, CircleUserRound, Clock3, CreditCard, Eye, EyeOff, FileCheck2, FilePlus2,
  Files, Flag, Home, LayoutDashboard, LockKeyhole, LogOut, MapPin, Menu, MessageSquareWarning,
  Search, ShieldCheck, Upload, UserCog, Users, X, XCircle
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable/index";
import sealAsset from "@/assets/sceau-cameroun.jfif.asset.json";
import flagAsset from "@/assets/drapeau-cameroun.jfif.asset.json";
import panoramaAsset from "@/assets/panorama-douala.jpg.asset.json";
import monumentAsset from "@/assets/monument-douala.jpg.asset.json";
import crossroadsAsset from "@/assets/carrefour-ville.jpg.asset.json";
import cityHallAsset from "@/assets/mairie-ville.jpg.asset.json";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

type View = "home" | "how" | "login" | "register" | "forgot" | "dashboard" | "new-request" | "request-form" | "request-files" | "request-confirm" | "tracking" | "appointment" | "appointments" | "new-report" | "reports" | "report-detail" | "profile" | "payment" | "agent" | "request-review" | "calendar-admin" | "report-review" | "admin" | "agents" | "agent-form" | "notifications";
type Role = "public" | "citizen" | "agent" | "admin";

const backgrounds = [panoramaAsset.url, monumentAsset.url, crossroadsAsset.url, cityHallAsset.url];
const publicViews: View[] = ["home", "how", "login", "register", "forgot"];
const viewTitles: Record<View, string> = {
  home: "Bienvenue", how: "Comment ça marche ?", login: "Connexion", register: "Créer mon compte", forgot: "Mot de passe oublié",
  dashboard: "Mon espace citoyen", "new-request": "Nouvelle demande", "request-form": "Informations de la demande", "request-files": "Pièces justificatives", "request-confirm": "Confirmation",
  tracking: "Suivi de mes demandes", appointment: "Prendre rendez-vous", appointments: "Mes rendez-vous", "new-report": "Nouveau signalement", reports: "Mes signalements", "report-detail": "Suivi de la plainte",
  profile: "Mon profil", payment: "Paiement", agent: "Espace agent", "request-review": "Traiter une demande", "calendar-admin": "Gestion des rendez-vous", "report-review": "Traiter un signalement",
  admin: "Administration", agents: "Gestion des agents", "agent-form": "Compte agent", notifications: "Notifications"
};

const mockRequests = [
  { ref: "DEM-2026-0148", type: "Acte de naissance", status: "En cours", date: "22 sept. 2026" },
  { ref: "DEM-2026-0132", type: "Certificat de résidence", status: "Traité", date: "18 sept. 2026" },
  { ref: "DEM-2026-0117", type: "Légalisation de document", status: "Reçu", date: "12 sept. 2026" },
];
const mockReports = [
  { ref: "SIG-2026-0084", type: "Éclairage public", status: "En cours", place: "Carrefour du marché" },
  { ref: "SIG-2026-0061", type: "Voirie", status: "Traité", place: "Rue des Manguiers" },
];

function Seal() {
  return <div className="seal"><img src={sealAsset.url} alt="Sceau de la République du Cameroun"/><strong>République du Cameroun</strong><span>Paix · Travail · Patrie</span></div>;
}

function Status({ children }: { children: string }) {
  const tone = children === "Traité" || children === "Confirmé" ? "done" : children === "Rejeté" ? "rejected" : children === "En cours" ? "progress" : "waiting";
  return <span className={`status ${tone}`}><span />{children}</span>;
}

function Field({ label, required = true, children }: { label: string; required?: boolean; children: React.ReactNode }) {
  return <label className="field"><span>{label}{required && <b> *</b>}</span>{children}</label>;
}

function PasswordInput({ value, onChange, placeholder = "Votre mot de passe", name = "password" }: { value: string; onChange: (v:string)=>void; placeholder?: string; name?: string }) {
  const [show, setShow] = useState(false);
  return <div className="password-wrap"><Input name={name} type={show ? "text" : "password"} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required minLength={8}/><button type="button" aria-label={show ? "Masquer le mot de passe" : "Afficher le mot de passe"} onClick={()=>setShow(!show)}>{show ? <EyeOff/> : <Eye/>}</button></div>;
}

function PageNav({ back, next, nextLabel = "Suivant", nextDisabled = false }: { back?: ()=>void; next?: ()=>void; nextLabel?: string; nextDisabled?: boolean }) {
  return <div className="page-nav"><Button variant="outline" onClick={back} disabled={!back}><ArrowLeft/> Retour</Button><Button onClick={next} disabled={!next || nextDisabled}>{nextLabel} <ArrowRight/></Button></div>;
}

function PublicHeader({ go }: { go:(v:View)=>void }) {
  return <header className="public-header"><button className="wordmark" onClick={()=>go("home")}><Building2/><span>Services municipaux</span></button><nav><button onClick={()=>go("home")}>Accueil</button><button onClick={()=>go("how")}>Comment ça marche</button><Button variant="outline" onClick={()=>go("login")}>Se connecter</Button><Button onClick={()=>go("register")}>Créer un compte</Button></nav></header>;
}

function Landing({ go }: { go:(v:View)=>void }) {
  return <main><section className="hero" style={{backgroundImage:`linear-gradient(90deg, var(--hero-overlay), var(--hero-overlay-soft)), url(${panoramaAsset.url})`}}><div className="hero-inner"><span className="eyebrow">Votre mairie, plus proche de vous</span><h1>Vos démarches municipales,<br/>simplement.</h1><p>Demandez un document, prenez rendez-vous ou signalez un problème depuis un espace unique et sécurisé.</p><div className="hero-actions"><Button size="lg" onClick={()=>go("register")}>Commencer une démarche <ArrowRight/></Button><Button size="lg" variant="outline" onClick={()=>go("how")}>Découvrir le fonctionnement</Button></div></div></section><section className="service-band"><div className="section-heading"><span>Services essentiels</span><h2>Que souhaitez-vous faire aujourd’hui ?</h2></div><div className="service-grid">{[[FilePlus2,"Demander un document","Actes, certificats et légalisations.","new-request"],[CalendarDays,"Prendre rendez-vous","Choisissez un service et un créneau.","appointment"],[MessageSquareWarning,"Signaler un problème","Voirie, éclairage, déchets ou doléance.","new-report"]].map(([Icon,title,text,target])=><button className="service-card" key={title as string} onClick={()=>go(target as View)}><Icon/><h3>{title as string}</h3><p>{text as string}</p><span>Accéder au service <ChevronRight/></span></button>)}</div></section></main>;
}

function How({ go }: { go:(v:View)=>void }) {
 const steps = [["01","Créez votre compte","Renseignez votre identité et vos coordonnées. Un e-mail de confirmation sécurise votre accès."],["02","Choisissez votre service","Demande de document, rendez-vous ou signalement : sélectionnez la démarche adaptée."],["03","Complétez votre dossier","Saisissez les informations demandées, puis ajoutez les pièces justificatives indiquées."],["04","Suivez l’avancement","Retrouvez chaque étape, les messages de l’agent et votre document final depuis votre espace."]];
 return <main className="photo-page" style={{backgroundImage:`linear-gradient(var(--photo-wash),var(--photo-wash)),url(${monumentAsset.url})`}}><div className="content-panel wide"><div className="section-heading"><span>Un parcours clair et accompagné</span><h1>Comment ça marche ?</h1><p>Quelques étapes suffisent pour accéder aux services de votre ville, sans déplacement inutile.</p></div><div className="steps">{steps.map(([n,t,d])=><div className="step" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><PageNav back={()=>go("home")} next={()=>go("register")} nextLabel="Créer mon compte"/></div></main>;
}

function AuthPanel({ mode, go, onAuthenticated }: { mode:"login"|"register"|"forgot"; go:(v:View)=>void; onAuthenticated:()=>void }) {
 const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const fd=new FormData(e.currentTarget); const email=String(fd.get("email")||"").trim();
   try { if(mode==="login"){ const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) throw error; toast.success("Connexion réussie"); onAuthenticated(); }
   else if(mode==="register"){ if(password!==confirm) throw new Error("Les mots de passe ne correspondent pas."); const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin,data:{full_name:String(fd.get("name")||""),phone:String(fd.get("phone")||""),cni_number:String(fd.get("cni")||"")}}}); if(error) throw error; setSent(true); }
   else { const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`}); if(error) throw error; setSent(true); }} catch(err){ toast.error(err instanceof Error?err.message:"Une erreur est survenue"); } finally {setBusy(false)} }
 async function google(){ const r=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin}); if(r.error) toast.error(r.error.message); else if(!r.redirected) onAuthenticated(); }
 const title=mode==="login"?"Heureux de vous revoir":mode==="register"?"Créer votre espace":"Retrouver votre accès";
 return <main className="auth-page" style={{backgroundImage:`linear-gradient(var(--auth-overlay),var(--auth-overlay)),url(${crossroadsAsset.url})`}}><form className="auth-card" onSubmit={submit}><div className="auth-title"><span>{mode==="login"?"Connexion":mode==="register"?"Inscription":"Assistance"}</span><h1>{title}</h1><p>{mode==="forgot"?"Indiquez l’adresse e-mail de votre compte. Vous recevrez un lien sécurisé pour créer un nouveau mot de passe.":"Accédez aux services municipaux de votre ville en toute sécurité."}</p></div>{sent?<div className="success-state"><CheckCircle2/><h2>Consultez votre messagerie</h2><p>{mode==="register"?"Un lien de confirmation vous a été envoyé pour activer votre compte.":"Le lien de réinitialisation vient de vous être envoyé."}</p><Button type="button" onClick={()=>go("login")}>Retour à la connexion</Button></div>:<>{mode==="register"&&<><Field label="Nom complet"><Input name="name" placeholder="Ex. Marie Ngo Mbele" required minLength={3}/></Field><div className="field-row"><Field label="Numéro de CNI"><Input name="cni" placeholder="Ex. 123456789" required/></Field><Field label="Téléphone"><Input name="phone" type="tel" placeholder="+237(000 000 000)" pattern="\+237\([0-9]{3} [0-9]{3} [0-9]{3}\)" required/></Field></div></>}<Field label="Adresse e-mail"><Input name="email" type="email" placeholder="vous@exemple.cm" required/></Field>{mode!=="forgot"&&<Field label="Mot de passe"><PasswordInput value={password} onChange={setPassword}/></Field>}{mode==="register"&&<Field label="Confirmer le mot de passe"><PasswordInput name="confirm" value={confirm} onChange={setConfirm} placeholder="Saisissez-le à nouveau"/></Field>}<Button className="full-button" disabled={busy}>{busy?"Veuillez patienter…":mode==="login"?"Se connecter":mode==="register"?"Créer mon compte":"Envoyer le lien"}</Button>{mode==="login"&&<><button type="button" className="text-link" onClick={()=>go("forgot")}>Mot de passe oublié ?</button><div className="separator"><span>ou</span></div><Button type="button" variant="outline" className="full-button" onClick={google}>Continuer avec Google</Button></>}</>}<div className="auth-switch">{mode==="login"?<>Pas encore de compte ? <button type="button" onClick={()=>go("register")}>S’inscrire</button></>:<>Déjà un compte ? <button type="button" onClick={()=>go("login")}>Se connecter</button></>}</div><PageNav back={()=>go(mode==="forgot"?"login":"home")} next={mode==="forgot"?()=>go("login"):undefined} nextLabel="Connexion"/></form></main>;
}

function Dashboard({ go }: { go:(v:View)=>void }) { return <div className="dashboard"><div className="welcome"><div><span>Bonjour,</span><h1>Bienvenue dans votre espace citoyen</h1><p>Retrouvez vos démarches et les services de votre ville en un coup d’œil.</p></div><Button onClick={()=>go("new-request")}><FilePlus2/> Nouvelle demande</Button></div><div className="stat-grid">{[[Files,"3","Demandes actives"],[CalendarDays,"1","Rendez-vous à venir"],[MessageSquareWarning,"2","Signalements"],[Bell,"4","Notifications"]].map(([Icon,n,l])=><div className="stat" key={l as string}><Icon/><div><b>{n as string}</b><span>{l as string}</span></div></div>)}</div><div className="dashboard-columns"><section><div className="panel-title"><h2>Demandes récentes</h2><button onClick={()=>go("tracking")}>Tout voir</button></div><div className="list">{mockRequests.map(r=><button key={r.ref} className="list-row" onClick={()=>go("tracking")}><FileCheck2/><div><b>{r.type}</b><span>{r.ref} · {r.date}</span></div><Status>{r.status}</Status><ChevronRight/></button>)}</div></section><section><div className="panel-title"><h2>Accès rapides</h2></div><div className="quick-grid"><button onClick={()=>go("appointment")}><CalendarDays/><span>Rendez-vous</span></button><button onClick={()=>go("new-report")}><MessageSquareWarning/><span>Signaler</span></button><button onClick={()=>go("profile")}><CircleUserRound/><span>Mon profil</span></button><button onClick={()=>go("notifications")}><Bell/><span>Notifications</span></button></div></section></div><PageNav back={()=>go("home")} next={()=>go("new-request")} nextLabel="Nouvelle demande"/></div> }

function RequestFlow({ step, go }: { step:1|2|3|4; go:(v:View)=>void }) { const [valid,setValid]=useState(false); const routes:View[]=["new-request","request-form","request-files","request-confirm"]; const titles=["Choisir un document","Renseigner les informations","Ajouter les pièces","Vérifier et envoyer"]; return <div className="form-screen"><div className="form-head"><span>Demande de document</span><h1>{titles[step-1]}</h1><div className="progress-line">{[1,2,3,4].map(n=><i key={n} className={n<=step?"active":""}>{n<step?<Check/>:n}</i>)}</div></div><form className="form-body" onChange={()=>setValid(true)}>{step===1&&<div className="choice-grid">{["Acte de naissance","Certificat de résidence","Légalisation","Autorisation municipale"].map((x,i)=><label className="choice" key={x}><input type="radio" name="doc" required defaultChecked={i===0}/><FileCheck2/><b>{x}</b><span>Délai indicatif : {i+2} jours ouvrés</span></label>)}</div>}{step===2&&<div className="fields-grid"><Field label="Nom complet"><Input required placeholder="Votre nom tel qu’indiqué sur la CNI"/></Field><Field label="Numéro de CNI"><Input required placeholder="Votre numéro de CNI"/></Field><Field label="Lieu concerné"><Input required placeholder="Votre ville"/></Field><Field label="Motif de la demande"><Textarea required placeholder="Précisez brièvement l’usage du document"/></Field></div>}{step===3&&<div className="upload-zone"><Upload/><h2>Ajoutez vos pièces justificatives</h2><p>CNI recto-verso et justificatif de domicile. Formats JPG, PNG ou PDF, 5 Mo maximum.</p><Input type="file" required accept="image/png,image/jpeg,application/pdf" onChange={e=>setValid(Boolean(e.target.files?.length))}/></div>}{step===4&&<div className="summary"><CheckCircle2/><h2>Votre dossier est prêt</h2><dl><div><dt>Document</dt><dd>Acte de naissance</dd></div><div><dt>Demandeur</dt><dd>Compte citoyen</dd></div><div><dt>Lieu</dt><dd>Votre ville</dd></div><div><dt>Pièces</dt><dd>2 fichiers joints</dd></div></dl><label className="consent"><input type="checkbox" required onChange={e=>setValid(e.target.checked)}/> Je certifie l’exactitude des informations fournies.</label></div>}</form><PageNav back={()=>go(step===1?"dashboard":routes[step-2])} next={()=>{if(step===4){toast.success("Demande envoyée avec succès");go("tracking")}else go(routes[step])}} nextLabel={step===4?"Envoyer la demande":"Suivant"} nextDisabled={step>1&&!valid}/></div> }

function Tracking({ go }: { go:(v:View)=>void }) { const [selected,setSelected]=useState(0); const r=mockRequests[selected]; return <div className="split-view"><section><div className="panel-title"><div><span>Mes dossiers</span><h1>Suivi des demandes</h1></div><div className="search"><Search/><Input placeholder="Rechercher une référence"/></div></div><div className="list">{mockRequests.map((item,i)=><button className={`request-tile ${selected===i?"selected":""}`} key={item.ref} onClick={()=>setSelected(i)}><div><b>{item.type}</b><span>{item.ref}</span></div><Status>{item.status}</Status><small>{item.date}</small></button>)}</div></section><aside className="detail"><div className="detail-head"><FileCheck2/><div><span>{r.ref}</span><h2>{r.type}</h2></div><Status>{r.status}</Status></div><div className="timeline">{[["Demande reçue","22 septembre à 09:16",true],["Vérification des pièces","23 septembre à 14:30",r.status!=="Reçu"],["Traitement par le service","Délai estimé : 2 jours",r.status==="En cours"||r.status==="Traité"],["Document disponible","Vous serez notifié",r.status==="Traité"]].map(([t,d,on],i)=><div className={on?"active":""} key={t as string}><i>{on?<Check/>:<Clock3/>}</i><p><b>{t as string}</b><span>{d as string}</span></p></div>)}</div><div className="info-note"><ShieldCheck/><p>Votre dossier est traité par le service d’état civil. Vous recevrez une notification à chaque changement.</p></div></aside><PageNav back={()=>go("dashboard")} next={()=>go("new-request")} nextLabel="Nouvelle demande"/></div> }

function Appointment({ list, go }: { list?:boolean; go:(v:View)=>void }) { const [slot,setSlot]=useState(""); if(list) return <div className="form-screen"><div className="form-head"><span>Agenda personnel</span><h1>Mes rendez-vous</h1></div><div className="list"><div className="appointment-card"><CalendarDays/><div><b>Service de l’état civil</b><span>Vendredi 25 septembre 2026 · 10:30</span><small>Hôtel de ville — Guichet 4</small></div><Status>Confirmé</Status><Button variant="outline" onClick={()=>toast.success("Rendez-vous annulé")}>Annuler</Button></div></div><PageNav back={()=>go("dashboard")} next={()=>go("appointment")} nextLabel="Nouveau rendez-vous"/></div>; return <div className="form-screen"><div className="form-head"><span>Réserver un créneau</span><h1>Prendre rendez-vous</h1></div><div className="fields-grid"><Field label="Service municipal"><select required><option>État civil</option><option>Urbanisme</option><option>Affaires sociales</option></select></Field><Field label="Motif"><Input required placeholder="Objet de votre rendez-vous"/></Field></div><h2 className="subheading">Créneaux disponibles</h2><div className="slots">{["09:00","09:45","10:30","13:30","14:15","15:00"].map(x=><button className={slot===x?"selected":""} onClick={()=>setSlot(x)} key={x}><Clock3/>{x}</button>)}</div><PageNav back={()=>go("dashboard")} next={()=>{toast.success("Rendez-vous confirmé");go("appointments")}} nextLabel="Confirmer" nextDisabled={!slot}/></div> }

function Reports({ detail=false, go }: { detail?:boolean; go:(v:View)=>void }) { if(detail) return <div className="form-screen"><div className="detail-head"><MessageSquareWarning/><div><span>SIG-2026-0084</span><h1>Éclairage public</h1></div><Status>En cours</Status></div><div className="report-map"><MapPin/><div><b>Carrefour du marché</b><span>Signalé le 21 septembre 2026 à 19:42</span></div></div><div className="response-box"><h2>Réponse du service technique</h2><p>Votre signalement a été transmis à l’équipe d’intervention. Une vérification du lampadaire est prévue dans les 48 heures.</p></div><div className="timeline compact"><div className="active"><i><Check/></i><p><b>Signalement reçu</b><span>21 septembre</span></p></div><div className="active"><i><Clock3/></i><p><b>Intervention planifiée</b><span>23 septembre</span></p></div><div><i><Clock3/></i><p><b>Résolution</b><span>À venir</span></p></div></div><PageNav back={()=>go("reports")} next={()=>go("dashboard")} nextLabel="Tableau de bord"/></div>; return <div className="form-screen"><div className="form-head"><span>Mes échanges avec la mairie</span><h1>Mes signalements</h1></div><div className="report-list">{mockReports.map(x=><div className="report-card" key={x.ref}><MessageSquareWarning/><div><b>{x.type}</b><span>{x.ref} · <MapPin/> {x.place}</span></div><Status>{x.status}</Status><Button onClick={()=>go("report-detail")}>Voir <ChevronRight/></Button></div>)}</div><PageNav back={()=>go("dashboard")} next={()=>go("new-report")} nextLabel="Nouveau signalement"/></div> }

function NewReport({ go }: { go:(v:View)=>void }) { const [ok,setOk]=useState(false); return <div className="form-screen"><div className="form-head"><span>Alerter les services municipaux</span><h1>Nouveau signalement</h1><p>Décrivez précisément la situation pour faciliter une intervention rapide.</p></div><form className="fields-grid" onChange={()=>setOk(true)}><Field label="Catégorie"><select required><option value="">Sélectionner</option><option>Voirie</option><option>Éclairage public</option><option>Déchets et salubrité</option><option>Autre doléance</option></select></Field><Field label="Localisation"><Input required placeholder="Quartier, rue ou point de repère"/></Field><Field label="Description"><Textarea required minLength={20} placeholder="Que se passe-t-il ? Depuis quand ?"/></Field><Field label="Photo" required={false}><Input type="file" accept="image/*"/></Field></form><PageNav back={()=>go("dashboard")} next={()=>{toast.success("Signalement transmis");go("reports")}} nextLabel="Envoyer" nextDisabled={!ok}/></div> }

function Profile({ go }: { go:(v:View)=>void }) { const [avatar,setAvatar]=useState<string>(); const [saved,setSaved]=useState(false); return <div className="form-screen"><div className="form-head"><span>Compte personnel</span><h1>Mon profil</h1></div><div className="profile-layout"><label className="avatar-upload">{avatar?<img src={avatar} alt="Photo de profil"/>:<CircleUserRound/>}<span><Camera/> Modifier la photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setAvatar(URL.createObjectURL(f))}}/></span></label><form className="fields-grid" onSubmit={e=>{e.preventDefault();setSaved(true);toast.success("Profil enregistré")}}><Field label="Nom complet"><Input defaultValue="Marie Ngo Mbele" required/></Field><Field label="Adresse e-mail"><Input type="email" defaultValue="marie@example.cm" required/></Field><Field label="Téléphone"><Input defaultValue="+237(690 000 000)" pattern="\+237\([0-9]{3} [0-9]{3} [0-9]{3}\)" required/></Field><Field label="Ville"><Input defaultValue="Votre ville" required/></Field><Field label="Adresse"><Input defaultValue="Quartier administratif" required/></Field><Button>{saved?<><Check/> Enregistré</>:"Enregistrer les modifications"}</Button></form></div><PageNav back={()=>go("dashboard")} next={()=>go("dashboard")} nextLabel="Terminer"/></div> }

function Payment({ go }: { go:(v:View)=>void }) { const [paid,setPaid]=useState(false); return <div className="form-screen narrow"><div className="form-head"><span>Règlement de la démarche</span><h1>Paiement sécurisé</h1></div>{paid?<div className="success-state"><CheckCircle2/><h2>Paiement enregistré</h2><p>Votre reçu est disponible dans votre espace.</p></div>:<form className="fields-grid" onSubmit={e=>{e.preventDefault();setPaid(true)}}><Field label="Nom du titulaire"><Input required/></Field><Field label="Numéro de transaction"><Input required inputMode="numeric" placeholder="0000 0000 0000"/></Field><Field label="Téléphone"><Input required placeholder="+237(000 000 000)"/></Field><div className="total"><span>Total</span><b>****** FCFA</b></div><Button><CreditCard/> Valider</Button></form>}<PageNav back={()=>go("request-confirm")} next={()=>go("tracking")} nextLabel="Voir le suivi"/></div> }

function Notifications({ go }: { go:(v:View)=>void }) { return <div className="form-screen"><div className="form-head"><span>Restez informé</span><h1>Notifications</h1></div><div className="notification-list">{[[CheckCircle2,"Votre demande avance","Le dossier DEM-2026-0148 est maintenant en cours de traitement.","Il y a 2 h"],[CalendarDays,"Rappel de rendez-vous","Votre rendez-vous est prévu demain à 10:30.","Hier"],[MessageSquareWarning,"Réponse à votre signalement","Le service technique a planifié une intervention.","22 sept."]].map(([Icon,t,d,time])=><div key={t as string}><Icon/><p><b>{t as string}</b><span>{d as string}</span></p><small>{time as string}</small></div>)}</div><PageNav back={()=>go("dashboard")} next={()=>go("dashboard")} nextLabel="Tableau de bord"/></div> }

function StaffDashboard({ admin=false, go }: { admin?:boolean; go:(v:View)=>void }) { return <div className={`staff-page ${admin?"admin-bg":""}`} style={admin?{backgroundImage:`linear-gradient(var(--flag-wash),var(--flag-wash)),url(${flagAsset.url})`}:undefined}><div className="staff-content"><div className="welcome"><div><span>{admin?"Pilotage municipal":"Service aux citoyens"}</span><h1>{admin?"Tableau de bord administrateur":"Tableau de bord agent"}</h1><p>{admin?"Vue consolidée de l’activité des services.":"Dossiers à examiner et interventions à coordonner."}</p></div>{admin&&<Button onClick={()=>go("agent-form")}><UserCog/> Ajouter un agent</Button>}</div><div className="stat-grid">{(admin?[[Users,"12","Agents actifs"],[Files,"286","Demandes ce mois"],[Clock3,"74%","Traitées à temps"],[MessageSquareWarning,"38","Signalements"]]:[[Files,"18","Dossiers reçus"],[Clock3,"7","En cours"],[CheckCircle2,"24","Traités"],[MessageSquareWarning,"5","Signalements"]]).map(([Icon,n,l])=><div className="stat" key={l as string}><Icon/><div><b>{n as string}</b><span>{l as string}</span></div></div>)}</div>{admin?<><div className="chart-panel"><div className="panel-title"><h2>Activité des 7 derniers jours</h2><span>Demandes traitées</span></div><div className="bars">{[42,68,54,82,71,92,64].map((n,i)=><div key={i}><i style={{height:`${n}%`}}/><span>{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"][i]}</span></div>)}</div></div><div className="quick-grid"><button onClick={()=>go("agents")}><Users/><span>Gérer les agents</span></button><button onClick={()=>go("agent")}><Files/><span>Superviser les dossiers</span></button><button onClick={()=>go("notifications")}><Bell/><span>Notifications</span></button></div></>:<><div className="filter-bar"><Input placeholder="Rechercher un dossier"/><select><option>Tous les statuts</option><option>Reçu</option><option>En cours</option></select></div><div className="list">{mockRequests.map(r=><button key={r.ref} className="list-row" onClick={()=>go("request-review")}><FileCheck2/><div><b>{r.type}</b><span>{r.ref} · Citoyen</span></div><Status>{r.status}</Status><span>Prendre en charge</span><ChevronRight/></button>)}</div></>}<PageNav back={()=>go("login")} next={()=>go(admin?"agents":"request-review")} nextLabel={admin?"Gérer les agents":"Traiter un dossier"}/></div></div> }

function Review({ kind, go }: { kind:"request"|"report"|"calendar"; go:(v:View)=>void }) { const [rejected,setRejected]=useState(false); return <div className="form-screen"><div className="form-head"><span>Espace agent</span><h1>{kind==="request"?"Traitement d’une demande":kind==="report"?"Traitement d’un signalement":"Gestion des rendez-vous"}</h1></div>{kind==="calendar"?<div className="agenda">{["09:00","09:45","10:30","13:30"].map((t,i)=><div key={t}><b>{t}</b><p><strong>{i%2?"Urbanisme":"État civil"}</strong><span>Citoyen · {i%2?"Permis":"Acte"}</span></p><Status>{i===2?"Reçu":"Confirmé"}</Status><Button variant="outline">{i===2?"Confirmer":"Voir"}</Button></div>)}</div>:<><div className="detail-grid"><div><span>Référence</span><b>{kind==="request"?"DEM-2026-0148":"SIG-2026-0084"}</b></div><div><span>Demandeur</span><b>Marie Ngo Mbele</b></div><div><span>Nature</span><b>{kind==="request"?"Acte de naissance":"Éclairage public"}</b></div><div><span>Reçu le</span><b>22 septembre 2026</b></div></div><div className="response-box"><h2>{kind==="request"?"Pièces du dossier":"Description et réponse"}</h2><p>{kind==="request"?"Copie CNI · Justificatif de domicile · Formulaire signé":"Lampadaire défectueux depuis plusieurs jours au carrefour du marché."}</p>{(kind==="report"||rejected)&&<Textarea required placeholder={rejected?"Motif du rejet obligatoire":"Rédiger la réponse adressée au citoyen"}/>}</div><div className="decision-buttons"><Button variant="outline" onClick={()=>setRejected(true)}><XCircle/> Rejeter</Button><Button onClick={()=>toast.success(kind==="request"?"Demande validée":"Réponse envoyée")}><CheckCircle2/> {kind==="request"?"Valider":"Envoyer la réponse"}</Button></div></>}<PageNav back={()=>go("agent")} next={()=>go(kind==="calendar"?"agent":kind==="request"?"calendar-admin":"agent")} /></div> }

function Agents({ form=false, go }: { form?:boolean; go:(v:View)=>void }) { if(form) return <div className="form-screen admin-surface" style={{backgroundImage:`linear-gradient(var(--flag-wash),var(--flag-wash)),url(${flagAsset.url})`}}><div className="form-head"><span>Administration</span><h1>Créer un compte agent</h1></div><form className="fields-grid" onSubmit={e=>{e.preventDefault();toast.success("Compte agent créé");go("agents")}}><Field label="Nom complet"><Input required/></Field><Field label="Adresse e-mail"><Input type="email" required/></Field><Field label="Rôle"><select required><option>Agent</option><option>Administrateur</option></select></Field><Field label="Service affecté"><select required><option>État civil</option><option>Urbanisme</option><option>Services techniques</option></select></Field><Button>Créer le compte</Button></form><PageNav back={()=>go("agents")} next={()=>go("admin")} nextLabel="Terminer"/></div>; return <div className="form-screen admin-surface" style={{backgroundImage:`linear-gradient(var(--flag-wash),var(--flag-wash)),url(${flagAsset.url})`}}><div className="form-head"><span>Administration</span><h1>Gestion des agents</h1></div><div className="agent-table">{[["Jean Mballa","État civil","Actif"],["Aïcha Njoya","Urbanisme","Actif"],["Paul Etoa","Services techniques","Inactif"]].map(a=><div key={a[0]}><CircleUserRound/><p><b>{a[0]}</b><span>{a[1]}</span></p><Status>{a[2]==="Actif"?"Traité":"Reçu"}</Status><Button variant="outline">Modifier</Button></div>)}</div><PageNav back={()=>go("admin")} next={()=>go("agent-form")} nextLabel="Ajouter un agent"/></div> }

function AppShell({ view, role, go, logout, children }: {view:View;role:Role;go:(v:View)=>void;logout:()=>void;children:React.ReactNode}) { const [menu,setMenu]=useState(false); const citizen=[[LayoutDashboard,"Accueil","dashboard"],[FilePlus2,"Nouvelle demande","new-request"],[Files,"Mes demandes","tracking"],[CalendarDays,"Rendez-vous","appointments"],[MessageSquareWarning,"Signalements","reports"],[CircleUserRound,"Mon profil","profile"]] as const; const agent=[[LayoutDashboard,"Tableau de bord","agent"],[Files,"Demandes","request-review"],[CalendarDays,"Rendez-vous","calendar-admin"],[MessageSquareWarning,"Signalements","report-review"]] as const; const admin=[[LayoutDashboard,"Vue d’ensemble","admin"],[Users,"Agents","agents"],[Files,"Supervision","agent"],[Bell,"Notifications","notifications"]] as const; const nav=role==="admin"?admin:role==="agent"?agent:citizen; return <div className="app-shell"><aside className={menu?"open":""}><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button><div className="side-title"><Building2/><div><b>Services municipaux</b><span>{role==="admin"?"Administration":role==="agent"?"Espace agent":"Espace citoyen"}</span></div></div><nav>{nav.map(([Icon,label,target])=><button key={target} className={view===target?"active":""} onClick={()=>{go(target);setMenu(false)}}><Icon/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut/> Se déconnecter</button></aside><div className="app-main"><header className="app-header"><button className="menu-toggle" onClick={()=>setMenu(true)}><Menu/></button><div className="location"><MapPin/><span>Votre ville</span></div><Seal/><div className="header-actions"><button onClick={()=>go("notifications")} aria-label="Notifications"><Bell/></button><button onClick={()=>go("profile")} aria-label="Profil"><CircleUserRound/></button></div></header><div className="page-content">{children}</div></div></div> }

export function CivicApp(){ const [view,setView]=useState<View>("home"); const [role,setRole]=useState<Role>("public"); const [history,setHistory]=useState<View[]>([]); const isPublic=publicViews.includes(view); const bg=backgrounds[Object.keys(viewTitles).indexOf(view)%backgrounds.length]; function go(v:View){setHistory(h=>[...h,view]);setView(v); if(["agent","request-review","calendar-admin","report-review"].includes(v))setRole("agent"); else if(["admin","agents","agent-form"].includes(v))setRole("admin"); else if(!publicViews.includes(v))setRole("citizen"); window.scrollTo({top:0,behavior:"smooth"});} function back(){const prev=history.at(-1)||"home";setHistory(h=>h.slice(0,-1));setView(prev)} async function logout(){await supabase.auth.signOut();setRole("public");setView("login")}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user){setRole("citizen");setView("dashboard")}})},[]);
 const page=useMemo(()=>{switch(view){case"home":return <Landing go={go}/>;case"how":return <How go={go}/>;case"login":case"register":case"forgot":return <AuthPanel mode={view} go={go} onAuthenticated={()=>go("dashboard")}/>;case"dashboard":return <Dashboard go={go}/>;case"new-request":return <RequestFlow step={1} go={go}/>;case"request-form":return <RequestFlow step={2} go={go}/>;case"request-files":return <RequestFlow step={3} go={go}/>;case"request-confirm":return <RequestFlow step={4} go={go}/>;case"tracking":return <Tracking go={go}/>;case"appointment":return <Appointment go={go}/>;case"appointments":return <Appointment list go={go}/>;case"new-report":return <NewReport go={go}/>;case"reports":return <Reports go={go}/>;case"report-detail":return <Reports detail go={go}/>;case"profile":return <Profile go={go}/>;case"payment":return <Payment go={go}/>;case"notifications":return <Notifications go={go}/>;case"agent":return <StaffDashboard go={go}/>;case"admin":return <StaffDashboard admin go={go}/>;case"request-review":return <Review kind="request" go={go}/>;case"calendar-admin":return <Review kind="calendar" go={go}/>;case"report-review":return <Review kind="report" go={go}/>;case"agents":return <Agents go={go}/>;case"agent-form":return <Agents form go={go}/>;}},[view]);
 return <div className="site" style={!isPublic&&role!=="admin"?{backgroundImage:`linear-gradient(var(--app-wash),var(--app-wash)),url(${bg})`}:undefined}>{isPublic?<><PublicHeader go={go}/><Seal/>{page}<footer><span>© 2026 Services municipaux · Votre ville</span><nav><button onClick={()=>go("how")}>Aide</button><button onClick={()=>go("agent")}>Espace agent</button><button onClick={()=>go("admin")}>Administration</button></nav></footer></>:<AppShell view={view} role={role} go={go} logout={logout}>{page}</AppShell>}<button className="back-float" onClick={back} aria-label="Revenir à la page précédente"><ArrowLeft/></button></div> }
